export const AUTH_USER_EXISTS = 'Пользователь с таким e-mail уже существует'
export const AUTH_USER_NOT_FOUND = 'Пользователь не найден'
export const AUTH_USER_PASSWORD_WRONG = 'Неправильный пароль!'
export const AUTH_USER_EMAIL_NOT_VALID = 'e-mail недействителен!'
export const AUTH_USER_BIRTH_DATE_NOT_VALID = 'Дата рождения недействительна!'